### ISSUE TITLE
When threshold is hit for CPU/Memory/Disk offer possible resolution options

### ISSUE THREAD

**Issue by chambrid** [ibm-cloud-solutions/hubot-ibmcloud-activity#17]
When a threshold for CPU/Memory/Disk is triggered in addition to notifying the user have the bot offer to take actions:
1) Scale instances/memory/disk
2) Restart app

**Comment by JonHoughton** [comment]
Opened issue on `hubot-ibmcloud-alerts`.  Closing this one.
