### ISSUE TITLE
need a way to store additional info for bot activity

### ISSUE THREAD

**Issue by aeweidne** [ibm-cloud-solutions/hubot-ibmcloud-activity#4]
Need a means to store arbitrary data with bot.activity stored in Elasticsearch. This data will be specific to certain bot activity. For example, for virtual server/container activity it would be nice to store the name of the VS/container for which the activity was performed on. This issue is to provide storage of a generic "activity_info" object within the bot.activity docs. Need to ensure all strings in this object are not_analyzed. Also need to enforce a naming pattern for the data stored in "activity_info" so mapping/field names are specific to the type of activity that took place.

**Comment by chambrid** [comment]
no, current push for this based on current usage.
